/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SPublicIdRouteImport } from './routes/s.$publicId'
import { Route as DeskPublicIdRouteImport } from './routes/desk.$publicId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SPublicIdRoute = SPublicIdRouteImport.update({
  id: '/s/$publicId',
  path: '/s/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskPublicIdRoute = DeskPublicIdRouteImport.update({
  id: '/desk/$publicId',
  path: '/desk/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/desk/$publicId': typeof DeskPublicIdRoute
  '/s/$publicId': typeof SPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/desk/$publicId': typeof DeskPublicIdRoute
  '/s/$publicId': typeof SPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/desk/$publicId': typeof DeskPublicIdRoute
  '/s/$publicId': typeof SPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/start' | '/terms' | '/desk/$publicId' | '/s/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/start' | '/terms' | '/desk/$publicId' | '/s/$publicId'
  id:
    | '__root__'
    | '/'
    | '/start'
    | '/terms'
    | '/desk/$publicId'
    | '/s/$publicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  DeskPublicIdRoute: typeof DeskPublicIdRoute
  SPublicIdRoute: typeof SPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$publicId': {
      id: '/s/$publicId'
      path: '/s/$publicId'
      fullPath: '/s/$publicId'
      preLoaderRoute: typeof SPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/$publicId': {
      id: '/desk/$publicId'
      path: '/desk/$publicId'
      fullPath: '/desk/$publicId'
      preLoaderRoute: typeof DeskPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  DeskPublicIdRoute: DeskPublicIdRoute,
  SPublicIdRoute: SPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
